#
# This source file is part of the ENGAGE-HF based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

default_platform(:ios)

platform :ios do
  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "5"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "6"
  end

  desc "Build and test"
  lane :test do
    run_tests(
      skip_build: true,
      derived_data_path: ".derivedData",
      code_coverage: true,
      devices: ["iPhone 15 Pro"],
      force_quit_simulator: true,
      reset_simulator: true,
      prelaunch_simulator: false,
      concurrent_workers: 1,
      max_concurrent_simulators: 1,
      result_bundle: true,
      output_directory: ".",
      xcargs: [
        "-skipPackagePluginValidation",
        "-skipMacroValidation"
      ]
    )
  end

  desc "Screenshots"
  lane :screenshots do
    run_tests(
      destination: "generic/platform=iOS Simulator",
      configuration: "Debug",
      derived_data_path: ".derivedData",
      xcargs: [
        "-skipPackagePluginValidation",
        "-skipMacroValidation"
      ],
      build_for_testing: true
    )

    snapshot(
      test_without_building: true,
      derived_data_path: ".derivedData",
      devices: [
        "iPhone 16 Pro Max"
      ],
      languages: [
         "en-US",
      ],
      scheme: "ENGAGEHF",
      output_directory: "./fastlane/screenshots",
      clear_previous_screenshots: true,
      concurrent_simulators: false,
      stop_after_first_error: true,
      skip_open_summary: true
    )
    
    # Workaround for https://github.com/fastlane/fastlane/issues/21759 and 
    Dir.glob("./screenshots/**/iPhone 16 Pro Max-*.png").each do |file|
      sh("sips --resampleHeightWidth 2796 1290 '#{file}'")
    end
  end

  desc "Build app"
  lane :build do
    build_app(
      skip_archive: true,
      skip_codesigning: true,
      derived_data_path: ".derivedData",
      xcargs: [
        "-skipPackagePluginValidation",
        "-skipMacroValidation"
      ]
    )
  end

  desc "Archive app"
  lane :archive do |options|
    appidentifier = options[:appidentifier] || "edu.stanford.bdh.engagehf"
    provisioningProfile = options[:provisioningProfile] || "Stanford BDHG ENGAGE-HF"

    update_app_identifier(
      plist_path: "ENGAGEHF/Supporting Files",
      app_identifier: appidentifier
    )

    build_app(
      derived_data_path: ".derivedData",
      xcargs: [
        "-skipPackagePluginValidation",
        "-skipMacroValidation"
      ],
      export_options: {
        provisioningProfiles: {
          appidentifier => provisioningProfile
        }
      }
    )
  end

  desc "Sign in to the App Store Connect API"
  lane :signin do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_BASE64"],
      is_key_content_base64: true
    )
  end

  desc "Publish a release to TestFlight or the App Store depending on the environment"
  lane :deploy do |options|
    environment = options[:environment] || "staging"
    appidentifier = options[:appidentifier] || "edu.stanford.bdh.engagehf"
    provisioningProfile = options[:provisioningProfile] || "Stanford BDHG ENGAGE-HF"
    
    signin
    increment_build_number(
      {
        build_number: latest_testflight_build_number + 1
      }
    )
    archive(
      appidentifier: appidentifier,
      provisioningProfile: provisioningProfile,
    )
    commit = last_git_commit
    
    if environment == "production"
      deliver(
        app_identifier: appidentifier,
        username: ENV["APPLE_ID"],
        submit_for_review: true,
        force: true,
        reject_if_possible: true,
        automatic_release: true,
        precheck_include_in_app_purchases: false,
      )
    else
      upload_to_testflight(
        app_identifier: appidentifier,
        apple_id: ENV["APPLE_ID"],
        distribute_external: true,
        groups: [
          "External Testers"
        ],
        submit_beta_review: true,
        notify_external_testers: true,
        changelog: commit[:message]
      )
    end
  end
end
