#
# This source file is part of the ENGAGE-HF based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
    permissions:
      contents: read
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
    permissions:
      contents: read
  markdownlinkcheck:
    name: Markdown Link Check
    uses: StanfordBDHG/.github/.github/workflows/markdown-link-check.yml@v2
    permissions:
      contents: read
  build_firebase_submodule:
    name: Build Firebase Submodule
    runs-on: ["macOS", "self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Dependencies
        run: npm --prefix ENGAGE-HF-Firebase run install
      - name: Build
        run: npm --prefix ENGAGE-HF-Firebase run build
  buildandtest:
    name: Build and Test
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@input/customfirebaseemulatorcommand
    permissions:
      contents: read
    with:
      artifactname: ENGAGEHF.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      fastlanelane: test
      setupfirebaseemulator: true
      checkout_submodules: true
      customfirebaseemulatorcommand: npm --prefix ENGAGE-HF-Firebase/functions run serve:seed
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: buildandtest
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    permissions:
      contents: read
    with:
      coveragereports: ENGAGEHF.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
